name: Build and push image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        export CODEQL_VERSION=$(head -n 1 ./codeql.version)
        docker build . --build-arg CODEQL_VERSION=${CODEQL_VERSION} --tag mionita22/codeql-java:${CODEQL_VERSION} --tag mionita22/codeql-java:latest
        docker push mionita22/codeql-java:${CODEQL_VERSION}
        docker push mionita22/codeql-java:latest
